### ISSUE TITLE
wish to add setOnItemClickListener function

### ISSUE THREAD

**Issue by lzhAndroid** [flschweiger/SwipeStack#4]
if item view setOnClick,it doesn't work

**Comment by flschweiger** [comment]
Currently it does not work because SwipeStack is intercepting the touch events. 
I will add this feature in a future release :wink:

**Comment by nambv** [comment]
I need it, true... waiting for your release :smile:

**Comment by casidiablo** [comment]
Are you already working on this or is it something you want to add down the road? I guess I can hack this myself, but if you are already on the works, then I rather wait.

**Comment by jsankar** [comment]
Hi, thank you for a superb library. I got a crash report today from Android 4.4.2.   Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:1979)
       at link.fls.SwipeHelper.onTouch(SwipeHelper.java:55)
       at android.view.View.dispatchTouchEvent(View.java:7772)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2013)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2350)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1985)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2109)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1541)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2491)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2057)
       at android.view.View.dispatchPointerEvent(View.java:7973)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4392)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4263)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3935)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3992)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6124)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6104)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6058)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6254)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)

**Comment by n1schal** [comment]
hey, was looking at this library and it's really very neat ! good work. eagerly looking forward to when the onItemClickListener is included. any news on when it'll be available? thanks!

**Comment by flschweiger** [comment]
Hey there, currently I'm on skiing holidays and I will look into it when I'm back home. Promised! :wink:

**Comment by n1schal** [comment]
thanks for the prompt response! for the time being i hacked my way into it ! enjoy your holidays ! :smile_cat:

**Comment by denwehrle** [comment]
do you still work on that feature? would be awesome to have!

**Comment by Aasaqt** [comment]
Is this feature added?

**Comment by langyazhouwl** [comment]
Is this feature added?It's really a nice library/.....

**Comment by matthew2402** [comment]
Something new about this?

**Comment by saintjab** [comment]
Hi guys, any update on this or anyone been able to implement the click event?

**Comment by ghost** [comment]
I'm able to implement click event unfortunately the click event appears behind the card for me.

**Comment by TheLester** [comment]
Also faced with this issue. I am able to set click listener to child view of topview swipeStack view, but its brokes onTouch - swipe logic
